#pragma once
#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 768

/**
키보드 우측 숫자패드가 방향 기준
*/
enum directionKind{
	DIRECTION_1,
	DIRECTION_2,
	DIRECTION_3,
	DIRECTION_4,
	DIRECTION_N,//중립
	DIRECTION_6,
	DIRECTION_7,
	DIRECTION_8,
	DIRECTION_9
};
#define MAX_DIRECTION DIRECTION_9+1